### ISSUE TITLE
新增DB data

### ISSUE THREAD

**Issue by ltsai471** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#13]
請問我們這次是不用實做 model.save() 的部分嗎? 不太清楚 data.json 要怎麼使用。

**Comment by chinyi0523** [comment]
data.json 助教已經幫你們打上db了，可以不用理會

**Comment by ric2k1** [comment]
MODE=Reset 後就會有資料，就可以開始測試，不用自己新增資料

**Comment by joshmtlau** [comment]
closing as stale issue
