### ISSUE TITLE
[typo] Fixed to resBlock 所以到底是searchBlock還是resBlock?

### ISSUE THREAD

**Issue by Eskartur** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#14]
![image](https://user-images.githubusercontent.com/91512127/204419382-656d0e38-9c29-4790-b27d-05f86fd9e684.png)
![image](https://user-images.githubusercontent.com/91512127/204419410-f6fbfb07-b4f5-44b9-8b6d-b70ca427dfe0.png)

**Comment by chinyi0523** [comment]
resBlock sorry for typo
