### ISSUE TITLE
reset mode 底下的資料筆數是0

### ISSUE THREAD

**Issue by yihsin9111** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#15]
在連上DB後的資料筆數好像是0(沒有更新到) 這樣是正常的嗎?
![image](https://user-images.githubusercontent.com/96363299/204420137-1abd45a8-0685-4ed5-b749-20b3eb81a007.png)
謝謝助教!

**Comment by JoshuaLau0220** [comment]
這個訊息是正常的，後面那個數字是原本資料庫裡面的資料筆數
我們提供的輸出可能太簡略了，不好意思
