### ISSUE TITLE
昨日以按照hack2準備但 無法yarn server

### ISSUE THREAD

**Issue by npes1010** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#17]
wp1111\hack2\backend> yarn server
yarn run v1.22.19
error Command "server" not found. Did you mean "semver"?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ric2k1** [comment]
檢查一下你的 backend/package.json?

**Comment by anitalu724** [comment]
看看用`yarn backend`能不能解決，因為package.json裡面應該沒有server這個指令，詳見README.md上 Prerequisite
