### ISSUE TITLE
GrapeScope沒辦法上傳壓縮檔

### ISSUE THREAD

**Issue by Sean217** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#19]
選取想上傳的hack2.zip後又跳回選取上傳檔案的頁面

**Comment by anitalu724** [comment]
@Sean217 請不要上傳整個hack2.zip，只要壓縮`frontend/src` 和`backend/src`即可，詳見README.md 下面submission

**Comment by Sean217** [comment]
感謝！！
