### ISSUE TITLE
1-3 回傳值定義問題

### ISSUE THREAD

**Issue by dupeicih** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#21]
請問GetSearch中error的情況，是指沒有找到符合的餐廳，還是其他系統的error呢？
error回傳的contents有什麼規定嗎？
謝謝！

**Comment by chinyi0523** [comment]
> 請問GetSearch中error的情況，是指沒有找到符合的餐廳，還是其他系統的error呢？ error回傳的contents有什麼規定嗎？ 謝謝！

系統錯誤，contents規定請從Readme推敲

**Comment by ric2k1** [comment]
error 時回傳的 content 就不重要，可以傳 [] 就好

**Comment by joshmtlau** [comment]
Closing as duplicated to #22
