### ISSUE TITLE
server.js 連線

### ISSUE THREAD

**Issue by poyu0124** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#23]
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1459:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 4000
}

**Comment by chinyi0523** [comment]
你的4000是不是有其他人在跑

**Comment by poyu0124** [comment]
如果有的話要如何關掉

**Comment by chinyi0523** [comment]
> 如果有的話要如何關掉

ctrl c

**Comment by joshmtlau** [comment]
closing as stale issue
