### ISSUE TITLE
server crash by module not supported

### ISSUE THREAD

**Issue by ruxiuhsiao** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#24]
想問一下執行sever得時候會遇到ES module 的問題要怎麼處理？還是這也算考試範圍....

<img width="820" alt="image" src="https://user-images.githubusercontent.com/40812662/204423542-dc2dcb38-063b-409a-8aa1-6e7ced6b4f10.png">

**Comment by ruxiuhsiao** [comment]
我遇到很多ES6或是其他版本不相容的問題....

**Comment by ric2k1** [comment]
那你之前的 HW6 可以連線嗎？

**Comment by ruxiuhsiao** [comment]
可以

**Comment by ruxiuhsiao** [comment]
好像每個作業裝出來的package.json不太一樣，同樣程式碼有的會error....

**Comment by ric2k1** [comment]
這次的 backend 也沒有特別裝什麼，你要不要把 code 改成跟 HW#6 那樣的連線試試看？

**Comment by ruxiuhsiao** [comment]
package的部分嗎？還是整個server.js?

**Comment by madmaxieee** [comment]
可以請你把目前的狀態 push 到 github 上嗎 這樣比較好瞭解你的狀況

**Comment by Miguel-618** [comment]
我也遇到一樣的問題

**Comment by madmaxieee** [comment]
你有 push 上來嗎

**Comment by Miguel-618** [comment]
push什麼

**Comment by ruxiuhsiao** [comment]
server.js還是error code?

**Comment by madmaxieee** [comment]
全部的 code

**Comment by ruxiuhsiao** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/40812662/204425371-ae47958a-daf2-457d-b800-ca13ba51d03a.png">
作業六的server.js

**Comment by ruxiuhsiao** [comment]
然後還是遇到一樣的問題，但hw6可以
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/40812662/204425437-4074d307-6938-415e-af10-179776518ee8.png">

**Comment by Miguel-618** [comment]
我push了

**Comment by madmaxieee** [comment]
請 push 到 github，跟交作業一樣

**Comment by ruxiuhsiao** [comment]
程式碼完全一樣，我目前用作業六的程式碼跑在作業六可以成功

**Comment by ruxiuhsiao** [comment]
push hack2到自己的github嗎？

**Comment by madmaxieee** [comment]
對

**Comment by ruxiuhsiao** [comment]
已push

**Comment by chinyi0523** [comment]
> 想問一下執行sever得時候會遇到ES module 的問題要怎麼處理？還是這也算考試範圍....
> 
> <img alt="image" width="820" src="https://user-images.githubusercontent.com/40812662/204423542-dc2dcb38-063b-409a-8aa1-6e7ced6b4f10.png">

@ruxiuhsiao 根據 #10 看看可不可以修正

**Comment by madmaxieee** [comment]
@Miguel-618 你是不是沒有 commit 到？我沒看到你的 package.json

**Comment by Miguel-618** [comment]
我是push整個hack2

**Comment by Miguel-618** [comment]
![image](https://user-images.githubusercontent.com/113119310/204426578-f0dbb251-5080-4d91-bdfc-8a7b5caf3d84.png)

**Comment by Miguel-618** [comment]
長這樣

**Comment by Miguel-618** [comment]
我好像可以跑了

**Comment by madmaxieee** [comment]
@ruxiuhsiao 
![CleanShot 2022-11-29 at 10 50 58](https://user-images.githubusercontent.com/76544194/204426819-d34eb57a-e83f-4274-9aed-3e88ad7ec066.png)
我看到的錯誤訊息之這樣 沒有這個檔案欸

**Comment by madmaxieee** [comment]
我把 import 不存在的檔案註解掉就過了？ @ruxiuhsiao

**Comment by ruxiuhsiao** [comment]
@madmaxieee 什麼意思？

**Comment by ruxiuhsiao** [comment]
哪個檔案ＱＱＱ 我現在遇到這個
<img width="835" alt="image" src="https://user-images.githubusercontent.com/40812662/204427853-b51323d6-aa93-4a8d-be90-ae3892e8db5b.png">

**Comment by ruxiuhsiao** [comment]
但是commentRoute是sample code的東西

**Comment by madmaxieee** [comment]
![CleanShot 2022-11-29 at 10 59 17](https://user-images.githubusercontent.com/76544194/204427961-1f6ed545-cec2-4b6a-b4c4-fc300ec1c9f4.png)
你推上來的東西沒有這個檔案

**Comment by ruxiuhsiao** [comment]
那是用hw6的server跑的嗎？在哪個檔案裡面有那行？
我現在改成hack2的server跑
但是會遇到這個問題
缺的東西是sample code的＠＠
我把目前的push檔案上去了
@madmaxieee 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/40812662/204428314-358b0a5f-1161-4257-930e-a78402a4f919.png">

**Comment by ric2k1** [comment]
@ruxiuhsiao 

要不要把 comments.js 改成

const GetCommentsByRestaurantId = ...
const CreateComment = ...

export default { GetCommentsByRestaurantId, CreateComment };

**Comment by madmaxieee** [comment]
{
  "name": "hugoeat",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "mongoose": "^5.10.15"
  },
  "scripts": {
    "server": "nodemon src/server.js --ext js --exec babel-node"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/cli": "^7.19.3",
    "@babel/core": "^7.20.2",
    "@babel/node": "^7.20.2",
    "@babel/preset-env": "^7.20.2",
    "babel-jest": "^29.3.0",
    "nodemon": "^2.0.6",
    "regenerator-runtime": "^0.13.10"
  }
}

**Comment by joshmtlau** [comment]
Closing as completed
