### ISSUE TITLE
無法連接後端

### ISSUE THREAD

**Issue by Lichi0404** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#25]
已經完成TODO1-3但後端仍無法連上 
<img width="620" alt="image" src="https://user-images.githubusercontent.com/113001576/204424140-6ee419b2-474c-4551-9af1-b9b52e798af8.png">

**Comment by chinyi0523** [comment]
https://stackoverflow.com/questions/61787468/error-while-parsing-config-json5-invalid-end-of-input-at-11-at-syntaxerror

**Comment by Lichi0404** [comment]
但我裡面並不是empty file

**Comment by joshmtlau** [comment]
closing as stale
