### ISSUE TITLE
cypress /api/getSearch returns search results'

### ISSUE THREAD

**Issue by misterSu514** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#27]
測資檢查時是檢查req.body 但如果照hackmd上面寫的會contents應該會在req.data裡 該如何解決

**Comment by chinyi0523** [comment]
> 測資檢查時是檢查req.body 但如果照hackmd上面寫的會contents應該會在req.data裡 該如何解決

是檢查 res.body不是 req.body，照著做應該會對
