### ISSUE TITLE
SyntaxError: The requested module './comment.js' does not  provide an export named 'default'

### ISSUE THREAD

**Issue by beatriceev** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#28]
import commentRoute from './comment.js'
       ^^^^^^^^^^^^
SyntaxError: The requested module './comment.js' does not 
provide an export named 'default'

**Comment by ric2k1** [comment]
你有裝 babel 嗎？有 .babelrc 嗎？

**Comment by beatriceev** [comment]
有的
![image](https://user-images.githubusercontent.com/72510080/204427912-81af5c3a-2264-4dd9-b8ab-0c64d849ced7.png)

**Comment by ric2k1** [comment]
要不要把 comments.js 改成

const GetCommentsByRestaurantId = ...
const CreateComment = ...

export default { GetCommentsByRestaurantId, CreateComment };
