### ISSUE TITLE
part1 第第二題

### ISSUE THREAD

**Issue by qaz159qaz159** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#30]
![image](https://user-images.githubusercontent.com/53325020/204425813-8a10f6bc-3265-4436-b030-65bafd688708.png)
如圖，第三題可以過但第二題不能過？

**Comment by chinyi0523** [comment]
請跑cypress試試看，如果有東西render錯就會沒過

**Comment by qaz159qaz159** [comment]
![image](https://user-images.githubusercontent.com/53325020/204426318-dc5874fb-6f43-4199-88a8-1219a0da4f2c.png)
但是我完全一樣，而且我就是跑cypress的？

**Comment by chinyi0523** [comment]
請看cypress的error message

**Comment by anitalu724** [comment]
@qaz159qaz159 請不要在issue上分享自己的code，謝謝配合～

**Comment by ckocp3** [comment]
請問 cypress 上寫
(10%) 2.  | Search page structure is the same as spec:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `div[id="0"]`, but never found it.
是正常的嗎？
SearchPage 的 restaurants 初始是空的，裡面好像都找不到東西

**Comment by chinyi0523** [comment]
> 

代表沒有正確render出restaurants

**Comment by ric2k1** [comment]
請多用 console.log(), 看看是哪個變數出問題

**Comment by ckocp3** [comment]
那請問做這題時有需要動到 restaurants 和 setRestaurant 嗎？
因為我印出 restaurants 一直是空的 array

**Comment by ckocp3** [comment]
如果將第一個 restaurant 的 data 放進 useState 的初始值的話，cypress 就會過了。所以想請問 restaurants 一直是空的是不是正常的？

**Comment by XXXaBg3619** [comment]
請問做完I-2後按Search介面會顯示什麼？

**Comment by chinyi0523** [comment]
> setRestaurant

這是考試範圍請自行判斷

**Comment by chinyi0523** [comment]
> 請問做完I-2後按Search介面會顯示什麼？

請先做完1-3

**Comment by chinyi0523** [comment]
> 那請問做這題時有需要動到 restaurants 和 setRestaurant 嗎？ 因為我印出 restaurants 一直是空的 array

請先做完1-3
