### ISSUE TITLE
cypress configuration file

### ISSUE THREAD

**Issue by jason501002** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#31]
我嘗試用npx和yarn去run cypress，但是系統顯示Could not find a Cypress configuration file in this folder:/code/wp/wp1111/hack2
但我確定這個路徑下有來自題目給的cypress檔案，想請問為什麼fail了

**Comment by joshmtlau** [comment]
除了`cypress/` 資料夾以外，也有 `cypress.config.js` 嗎？

**Comment by jason501002** [comment]
沒有ww
原來如此，謝謝
