### ISSUE TITLE
backend錯誤訊息

### ISSUE THREAD

**Issue by Jenjenll** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#33]
<img width="781" alt="截圖 2022-11-29 10 45 46" src="https://user-images.githubusercontent.com/75842513/204426390-5bac0f1a-a3ba-44cf-9cd6-d581db620d19.png">

**Comment by chinyi0523** [comment]
請確認babelrc是正確安裝的

**Comment by Jenjenll** [comment]
不好意思，修改後還是出現如下錯誤
<img width="785" alt="截圖 2022-11-29 11 06 59" src="https://user-images.githubusercontent.com/75842513/204429080-b3bee33e-8bf3-48f8-8ff5-b2c58c623a9e.png">

**Comment by chinyi0523** [comment]
請確認已經寫完 I-3
