### ISSUE TITLE
無法 yarn backend

### ISSUE THREAD

**Issue by tsailawrence** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#35]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/45750993/204427017-0e10796c-68bd-4a8a-a5fe-0af930635430.png">

**Comment by tsailawrence** [comment]
確定都有裝 express

**Comment by chinyi0523** [comment]
請確認babelrc是正確安裝的

**Comment by ric2k1** [comment]
請確認有 .babelrc 這個檔案
