### ISSUE TITLE
無法連接DB: code: 'MODULE_NOT_FOUND',

### ISSUE THREAD

**Issue by wwchin** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#38]
已經完成 I-3 但無法連接 DB
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/105462885/204429621-cabb08ea-1e09-486b-9842-d67db2816f19.png">

**Comment by chinyi0523** [comment]
請檢查../data.json有在正確位置上

**Comment by joshmtlau** [comment]
closing as stale
