### ISSUE TITLE
backend error

### ISSUE THREAD

**Issue by Lichi0404** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#4]
將.env弄好後要yarn server 但出現以下錯誤
ConfigError: Error while parsing config - JSON5: invalid end of input at 1:1
<img width="513" alt="image" src="https://user-images.githubusercontent.com/113001576/204416054-f0387711-8e87-4b98-aa55-676e5a1a72d1.png">

**Comment by ric2k1** [comment]
建議把 backend 的 code 寫好後再來測後端哦！ (Up to TODO I-3)
