### ISSUE TITLE
part1疑問

### ISSUE THREAD

**Issue by Str367** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#41]
想問一下
如果1.3過了 1.1跟1.2卻沒過可能是什麼狀況
我看網址欄也有成功轉移到http://localhost:3000/search上

**Comment by chinyi0523** [comment]
請跑cypress自行測試看看

**Comment by ric2k1** [comment]
可以參考 cypress/e2e/public-part1.cy.js 內的測試內容
