### ISSUE TITLE
有關setPriceFilter, setMealFilter等useState問題

### ISSUE THREAD

**Issue by Joey-Chiu** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#43]
在navigationBar.js裡面<Filter priceFilter={priceFilter} setPriceFilter={setPriceFilter} 這邊我們有需要對setPriceFilter進行操作嗎? 因為我實際操作react frontend，點那些filter勾勾 console.log出來好像value都是空白的qq
另外如果frontend App打開，視窗沒有全螢幕會有影響嗎?
<img width="956" alt="image" src="https://user-images.githubusercontent.com/81873335/204430954-3f5f12e6-2c00-46bd-982d-abe248702b1a.png">

**Comment by chinyi0523** [comment]
只需要在有寫todo的地方寫就好了
