### ISSUE TITLE
gradescope 無法上傳

### ISSUE THREAD

**Issue by Beer-and-Skittles** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#44]
嘗試在 gradescope 上傳 .zip 檔時無法將檔案 upload。會一直卡在這個畫面:
![image](https://user-images.githubusercontent.com/53812829/204431401-e4337a73-ac27-47e8-bb45-3c00059817dd.png)

**Comment by chinyi0523** [comment]
請多加嘗試，操作是對的

**Comment by Beer-and-Skittles** [comment]
助教您好，嘗試了許久還是一樣無法上傳

**Comment by joshmtlau** [comment]
請問你的壓縮方式是什麼呢？是否有包到兩個資料夾的src以外的東西呢？

**Comment by Beer-and-Skittles** [comment]
沒有 只有frontend backend 的 src 資料夾

**Comment by ric2k1** [comment]
是 frontend/src 跟 backend/src 嗎？

**Comment by Beer-and-Skittles** [comment]
上傳成功了!
