### ISSUE TITLE
filter行為疑問

### ISSUE THREAD

**Issue by headheadhead-csie** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#46]
請問filter是空的跟filter全部勾起來，意思都是全部顯示嗎?

**Comment by headheadhead-csie** [comment]
大概知道filter勾起來代表只顯示那項，但不確定filter是空的時候行為是如何

**Comment by chinyi0523** [comment]
> 大概知道filter勾起來代表只顯示那項，但不確定filter是空的時候行為是如何

請看Readme裡面有說明

**Comment by headheadhead-csie** [comment]
感謝 看到了
