### ISSUE TITLE
3-1 疑問

### ISSUE THREAD

**Issue by itsalicelee** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#48]
請問3-1 是只要點擊resBlock可以navigate就有分數嗎？(例如id = 0 要導到http://localhost:3000/restaurant/0)
我自己測試有成功但是gradescope上面顯示沒有分數QQ

**Comment by chinyi0523** [comment]
請確認到 http://localhost:3000/restaurant/0 有顯示出店家名稱
