### ISSUE TITLE
不能 yarn frontend

### ISSUE THREAD

**Issue by tsailawrence** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#5]
yarn run v1.22.19
warning ../../../../package.json: No license field
$ cd ./frontend && yarn start
warning ../../../../../package.json: No license field
$ react-scripts start
/bin/sh: react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chinyi0523** [comment]
/bin/sh: react-scripts: command not found

請確認都有正確yarn 或npm install

**Comment by CHENPINCHIEH** [comment]
已經確定npm install，也遇到一樣問題

**Comment by chinyi0523** [comment]
請把node_modules刪掉重新yarn一次

**Comment by CHENPINCHIEH** [comment]
> 請把node_modules刪掉重新yarn一次

還是一樣，但如果cd 到frontend start是可以的...

**Comment by chinyi0523** [comment]
> > 請把node_modules刪掉重新yarn一次
> 
> 還是一樣，但如果cd 到frontend start是可以的...

那你先這樣操作
