### ISSUE TITLE
Problem 1-2 

### ISSUE THREAD

**Issue by MrEast1203** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#54]
1) (10%) 2.  | Search page structure is the same as spec
有跟所有要求出寫，網頁顯示也正確，但grasscrope不通過
cypress顯示
AssertionError: Timed out retrying after 4000ms: Expected to find element: `p`, but never found it. Queried from element: [ <div.title>, 1 more... ]

**Comment by ric2k1** [comment]
你有按照 DOM structure 回傳嗎？

也可以參考 cypress/e2e/public-part1.cy.js 裡頭的測試結構

**Comment by MrEast1203** [comment]
有找到問題所在了謝謝
