### ISSUE TITLE
components/filter.js 跑不出來

### ISSUE THREAD

**Issue by Str367** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#57]
檔案都沒有動過
但是在網站上只要有勾隨便一個選項都會跳Cannot read properties of undefined (reading 'includes')這個錯誤
請問這是正常的嗎

**Comment by joshmtlau** [comment]
如果你沒有動navigate 裏面的 undefined 的話是正常的

**Comment by chinyi0523** [comment]
請問你是不是傳了錯的東西進去，請用console.log() 看看
