### ISSUE TITLE
git add不讓我更新最新的檔案

### ISSUE THREAD

**Issue by misterSu514** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#59]
[顯示fatal error](fatal: adding files failed)

**Comment by joshmtlau** [comment]
這個問題的可能成因太多 建議同學先不要 `git add .` 一次加一些檔案看看是哪個檔案的問題

**Comment by misterSu514** [comment]
助教我後來發現是cypress造成git add出錯 把cypress資料夾刪掉後就順利push上去了 但是我在時間結束前就一直在嘗試push  但12:37分左右才順利push上去 我的資料在時間結束後除了把cypress刪掉外其餘都沒動 想請問這樣還會有分數懲罰嗎

**Comment by joshmtlau** [comment]
因為最後延到12:50截止 因此同學不用擔心
為維持版面整潔，我先把這個issue關掉
