### ISSUE TITLE
export 'Routes' (imported as 'Routes') was not found in 'react-router-dom'

### ISSUE THREAD

**Issue by Glen-Chen-Blue** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#6]
在一開始yarn frondend得到
export 'Routes' (imported as 'Routes') was not found in 'react-router-dom' (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Prompt, Redirect, Route, Router, StaticRouter, Switch, generatePath, matchPath, useHistory, useLocation, useParams, useRouteMatch, withRouter)

**Comment by chinyi0523** [comment]
請確認你有在前端 yarn add react-router-dom

**Comment by Glen-Chen-Blue** [comment]
他說我node版本不相容，要怎麼解決

**Comment by chinyi0523** [comment]
刪掉node_modules然後重新yarn

**Comment by Glen-Chen-Blue** [comment]
還是錯誤

**Comment by chinyi0523** [comment]
https://meet.google.com/wdo-mmvt-pvp

**Comment by chinyi0523** [comment]
更新node到18
