### ISSUE TITLE
怎麼關掉cypress

### ISSUE THREAD

**Issue by fuffy1020** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#61]
助教您好，我跑了cypress但跑完了卻關不掉，導致我無法上傳到github

**Comment by fuffy1020** [comment]
我是windows系統

**Comment by madmaxieee** [comment]
ctrl + c ?

**Comment by madmaxieee** [comment]
或是直接把你的 terminal 關掉，如果他真的卡死的話

**Comment by fuffy1020** [comment]
助教您好
我後來發現是要把他裡面的截圖跟影片刪掉才能上傳github……
請問要怎麼解決這個部分，不然每跑一次cypress都要手動刪除
謝謝助教

莊加旭 (Max Chuang) ***@***.***> 於 2022年11月29日 週二 12:50 寫道：

**Comment by madmaxieee** [comment]
你可以那個資料夾加到 gitignore 裡面就好了，git 就不會去管那個裡面放什麼
