### ISSUE TITLE
Cypress pass but gradescope keep getting 10/100

### ISSUE THREAD

**Issue by Michael0303** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#66]
本地測試cypress已經能全部通過，而gradescope在剛完成part1時有拿過30分以上，但是之後的嘗試都只拿到10分，gradescope顯示只有1-3a.通過，麻煩助教幫忙看看問題在哪。我的學號是b08902018，感謝。

**Comment by chinyi0523** [comment]
請不要自行安裝套件vue

**Comment by Michael0303** [comment]
感謝助教，vscode不小心自動加入了。
