### ISSUE TITLE
請問 README.md Part II 這邊是寫錯嗎

### ISSUE THREAD

**Issue by tyl2018** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#74]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/46060952/204552526-00dab5b2-79cc-4c89-adff-606a2d5de33e.png">
如圖，框起來的地方應該是 American 對嗎？

**Comment by chinyi0523** [comment]
是 請修正為American ，抱歉這是我們的疏失
