### ISSUE TITLE
Yarn backend error: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by SeanFuEE** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#8]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/90328242/204416960-4452f387-cb89-4f94-b5ba-b9d41c55e5c5.png">

**Comment by chinyi0523** [comment]
請確認.babelrc 有正確新增完成

**Comment by JoshuaLau0220** [comment]
更改標題以跟另一個常見問題區別

**Comment by ric2k1** [comment]
這個很明顯就是沒有 .babelrc 吧？
