### ISSUE TITLE
Yarn frontend錯誤訊息

### ISSUE THREAD

**Issue by JennyLu19487** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#9]
yarn run v1.22.19
$ cd frontend && yarn start
$ react-scripts start
/bin/sh: react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by anitalu724** [comment]
請確認是否有正確執行過`yarn install`，或者把node_modules刪掉重做一次`yarn install`

**Comment by anitalu724** [comment]
詳見 #5
